[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "ChQAkMgywFmdYq1538UJc2yuLRVuskHhfceE8TBGFixx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
